(() => {
  const CATEGORIES=["仕入","酒類","出前","タバコ","消耗品","広告宣伝費","交通費","接待交際費","家賃","水道光熱費","通信費","給与関連","外注費","その他"];
  let financeMonth=null,financeTab="summary",financeExpenses=[],financeReceipts=[],editingExpenseId=null;
  const categoryOptions=value=>CATEGORIES.map(x=>`<option ${x===value?"selected":""}>${esc(x)}</option>`).join("");
  const monthBounds=month=>({start:`${month}-01`,end:dateString(new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0))});
  const receiptFor=id=>financeReceipts.find(r=>r.expense_id===id);
  const safeName=name=>String(name||"receipt").replace(/[^a-zA-Z0-9._-]/g,"_").slice(-80);

  async function loadFinanceExpenses(){
    if(!isOwner())return financeExpenses=financeReceipts=[];
    const [expenseResult,receiptResult]=await Promise.all([
      db.from("expenses").select("*").eq("store_id",storeId).is("deleted_at",null).order("expense_date",{ascending:false}).order("created_at",{ascending:false}).limit(500),
      db.from("expense_receipts").select("*").eq("store_id",storeId).order("created_at",{ascending:false}).limit(500)
    ]);
    if(expenseResult.error)throw expenseResult.error;if(receiptResult.error)throw receiptResult.error;
    financeExpenses=expenseResult.data||[];financeReceipts=receiptResult.data||[];
  }

  async function monthlyFinance(month=financeMonth){const {data,error}=await db.rpc("get_owner_monthly_finance",{target_store_id:storeId,target_month:`${month}-01`});if(error)throw error;return data||{}}
  const metric=(label,value,sub="")=>`<div class="metric"><div class="key">${label}</div><div class="value">${value}</div>${sub?`<div class="sub">${sub}</div>`:""}</div>`;

  function injectStyle(){const style=document.createElement("style");style.textContent=`
    .finance-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:11px}.finance-tabs button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.finance-tabs button.active{background:var(--navy);color:#fff}.finance-month{display:grid;grid-template-columns:1fr auto;gap:8px}.finance-summary-main{border-top:3px solid var(--gold)}.finance-summary-main .value{font-size:28px}.expense-card{padding:14px;border-bottom:1px solid var(--line)}.expense-card:last-child{border:0}.expense-vendor{font-weight:850}.expense-meta{margin-top:4px;color:var(--muted);font-size:11px}.expense-actions{display:flex;gap:7px;margin-top:10px}.expense-actions button{min-height:40px}.receipt-button{color:var(--navy);font-weight:850}.finance-category-row{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid var(--line)}.finance-category-row:last-child{border:0}.finance-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.finance-note{font-size:11px;color:var(--muted);line-height:1.6}.owner-finance-home .metrics{margin-bottom:8px}@media(max-width:430px){.finance-form-grid{grid-template-columns:1fr}.finance-tabs{grid-template-columns:1fr 1fr 1fr}}
  `;document.head.appendChild(style)}

  async function renderFinance(){
    const root=$("ownerFinanceRoot");if(!root)return;if(!isOwner()){root.innerHTML='<div class="empty">この画面はオーナーのみ利用できます</div>';return}if(!financeMonth)financeMonth=businessDateString().slice(0,7);
    root.innerHTML='<div class="empty">読み込み中...</div>';
    try{await loadFinanceExpenses();const summary=await monthlyFinance();root.innerHTML=`<div class="finance-tabs"><button data-ft="summary" class="${financeTab==="summary"?"active":""}">月次収支</button><button data-ft="expenses" class="${financeTab==="expenses"?"active":""}">経費</button><button data-ft="export" class="${financeTab==="export"?"active":""}">税理士用</button></div><div class="card"><div class="finance-month"><input type="month" id="financeMonth" value="${financeMonth}"><button class="small-btn" id="financeMonthApply">表示</button></div></div><div id="financeBody"></div>`;root.querySelectorAll("[data-ft]").forEach(b=>b.onclick=()=>{financeTab=b.dataset.ft;void renderFinance()});$("financeMonthApply").onclick=()=>{financeMonth=$("financeMonth").value||financeMonth;void renderFinance()};if(financeTab==="summary")renderFinanceSummary(summary);if(financeTab==="expenses")renderExpenseManager();if(financeTab==="export")renderFinanceExport()}catch(e){root.innerHTML=`<div class="status show error">${esc(e.message||String(e))}</div>`}
  }

  function renderFinanceSummary(s){const sales=Number(s.total_sales||0),expense=Number(s.expense_total||0),supply=Number(s.supply_expense||0),goal=Number(s.monthly_goal||0),profit=sales-expense,gross=sales-supply,categories=Array.isArray(s.category_expenses)?s.category_expenses:[];$("financeBody").innerHTML=`<div class="metric finance-summary-main"><div class="key">利益の参考値</div><div class="value">${signedYen(profit)}</div><div class="sub">売上実績 − 登録経費（税務上の利益ではありません）</div></div><div class="metrics">${metric("総売上",yen(sales),"精算済み・出前等控除後")}${metric("経費合計",yen(expense))}${metric("現金売上",yen(s.cash_sales))}${metric("カード売上",yen(s.card_sales))}${metric("その他決済",yen(s.other_sales))}${metric("未収金額",yen(s.unpaid_amount),`${s.unpaid_count||0}件`)}${metric("未収回収額",yen(s.collected_unpaid),"履歴記録開始後")}${metric("粗利の参考値",signedYen(gross),"売上 − 仕入・酒類")}${metric("月間目標",goal?yen(goal):"未設定")}${metric("目標まで",goal?yen(Math.max(goal-sales,0)):"－",goal&&sales>=goal?"達成済み":"")}</div><div class="card"><div class="section-title">カテゴリ別経費</div>${categories.length?categories.map(x=>`<div class="finance-category-row"><span>${esc(x.category)}</span><strong>${yen(x.amount)}</strong></div>`).join(""):'<div class="empty">経費なし</div>'}</div><div class="finance-note">粗利・利益は経営確認用の参考値です。税額・申告上の所得を示すものではありません。</div>`}

  function expenseForm(expense=null){return `<div class="card"><div class="section-title">${expense?"経費を編集":"経費を登録"}</div><div class="finance-form-grid"><div class="field"><label>日付 ※</label><input type="date" id="finExpenseDate" value="${expense?.expense_date||dateString()}"></div><div class="field"><label>金額 ※</label><input type="number" inputmode="numeric" min="1" id="finExpenseAmount" value="${expense?.amount||""}"></div></div><div class="field"><label>支払先</label><input id="finExpenseVendor" maxlength="120" value="${esc(expense?.vendor||"")}"></div><div class="finance-form-grid"><div class="field"><label>経費カテゴリ ※</label><select id="finExpenseCategory">${categoryOptions(expense?.category||"その他")}</select></div><div class="field"><label>支払方法 ※</label><select id="finExpenseMethod"><option ${expense?.payment_method==="現金"?"selected":""}>現金</option><option ${expense?.payment_method==="カード"?"selected":""}>カード</option><option ${expense?.payment_method==="振込"?"selected":""}>振込</option><option ${expense?.payment_method==="その他"?"selected":""}>その他</option></select></div></div><div class="field"><label>領収書画像</label><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" id="finExpenseReceipt"></div><div class="field"><label>メモ</label><textarea id="finExpenseMemo" maxlength="500">${esc(expense?.memo||"")}</textarea></div><div class="field"><label>税理士用科目（任意）</label><input id="finAccountingCategory" value="${esc(expense?.accounting_category||"")}" placeholder="税理士確認後に設定"></div><button class="primary" id="saveFinanceExpense">${expense?"変更を保存":"経費を登録"}</button>${expense?'<button class="secondary" id="cancelExpenseEdit" style="margin-top:8px">編集をやめる</button>':""}<div class="finance-note" style="margin-top:8px">現金払いだけレジ金から差し引きます。OCRによる自動確定は行いません。</div></div>`}
  function renderExpenseManager(){const {start,end}=monthBounds(financeMonth),rows=financeExpenses.filter(x=>x.expense_date>=start&&x.expense_date<=end),total=rows.reduce((a,x)=>a+Number(x.amount),0),editing=financeExpenses.find(x=>x.id===editingExpenseId);$("financeBody").innerHTML=`${expenseForm(editing)}<div class="metric"><div class="key">${financeMonth.replace("-","年")}月の経費</div><div class="value">${yen(total)}</div><div class="sub">${rows.length}件</div></div><div class="list">${rows.length?rows.map(x=>{const receipt=receiptFor(x.id);return`<div class="expense-card"><div class="item-top"><div><div class="expense-vendor">${esc(x.vendor||"支払先未入力")}</div><div class="expense-meta">${x.expense_date} ・ ${esc(x.category)} ・ ${esc(x.payment_method)} ・ ${receipt?"領収書あり":"領収書なし"}</div></div><div class="item-amount">${yen(x.amount)}</div></div>${x.memo?`<div class="note">${esc(x.memo)}</div>`:""}<div class="expense-actions">${receipt?`<button class="small-btn receipt-button" data-receipt="${receipt.id}">領収書を見る</button>`:""}<button class="small-btn" data-edit-expense="${x.id}">編集</button><button class="small-btn danger" data-delete-expense="${x.id}">削除</button></div></div>`}).join(""):'<div class="empty">この月の経費はありません</div>'}</div>`;$("saveFinanceExpense").onclick=saveExpense;$("cancelExpenseEdit")?.addEventListener("click",()=>{editingExpenseId=null;renderExpenseManager()});$("financeBody").querySelectorAll("[data-edit-expense]").forEach(b=>b.onclick=()=>{editingExpenseId=b.dataset.editExpense;renderExpenseManager();window.scrollTo({top:0,behavior:"smooth"})});$("financeBody").querySelectorAll("[data-delete-expense]").forEach(b=>b.onclick=()=>deleteExpense(b.dataset.deleteExpense));$("financeBody").querySelectorAll("[data-receipt]").forEach(b=>b.onclick=()=>openReceipt(b.dataset.receipt))}

  async function saveExpense(){const id=editingExpenseId,date=$("finExpenseDate").value,amount=Number($("finExpenseAmount").value),vendor=$("finExpenseVendor").value.trim(),category=$("finExpenseCategory").value,method=$("finExpenseMethod").value,memo=$("finExpenseMemo").value.trim(),accounting=$("finAccountingCategory").value.trim(),file=$("finExpenseReceipt").files[0],button=$("saveFinanceExpense");if(!date||!Number.isInteger(amount)||amount<=0)return showStatus("日付と1円以上の金額を確認してください","error");if(file&&file.size>10485760)return showStatus("領収書画像は10MB以下にしてください","error");button.disabled=true;button.textContent="保存中…";const fn=id?"update_store_expense":"create_store_expense",args=id?{target_store_id:storeId,target_expense_id:id,target_expense_date:date,target_amount:amount,target_vendor:vendor,target_category:category,target_payment_method:method,target_memo:memo,target_accounting_category:accounting}:{target_store_id:storeId,target_expense_date:date,target_amount:amount,target_vendor:vendor,target_category:category,target_payment_method:method,target_memo:memo,target_accounting_category:accounting};const {data,error}=await db.rpc(fn,args);if(error){button.disabled=false;button.textContent=id?"変更を保存":"経費を登録";return showStatus(error.message||"経費を保存できませんでした","error")}const expense=data;if(file){const path=`${storeId}/${expense.id}/${Date.now()}-${safeName(file.name)}`,uploaded=await db.storage.from("expense-receipts").upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error){showStatus("経費は保存しましたが、領収書画像を保存できませんでした","warning")}else{const receipt=await db.from("expense_receipts").insert({store_id:storeId,expense_id:expense.id,storage_path:path,original_filename:file.name,mime_type:file.type,file_size:file.size,created_by:currentAuthUser.id});if(receipt.error)showStatus("画像は保存しましたが、経費との紐付けに失敗しました","warning")}}editingExpenseId=null;await loadAll();await renderFinance();showStatus("経費を保存しました","success")}
  async function deleteExpense(id){if(!(await appConfirm("この経費を削除しますか？現金払いの場合はレジ金へ戻し、削除履歴を残します。","削除する")))return;const {error}=await db.rpc("delete_store_expense",{target_store_id:storeId,target_expense_id:id});if(error)return showStatus(error.message||"経費を削除できませんでした","error");await loadAll();await renderFinance();showStatus("経費を削除しました","success")}
  async function openReceipt(id){const receipt=financeReceipts.find(x=>x.id===id);if(!receipt)return;const {data,error}=await db.storage.from("expense-receipts").createSignedUrl(receipt.storage_path,120);if(error)return showStatus("領収書を開けませんでした","error");window.open(data.signedUrl,"_blank","noopener")}

  function csvCell(value){return `"${String(value??"").replaceAll('"','""')}"`}
  function downloadCsv(name,headers,rows){const csv="\ufeff"+[headers,...rows].map(row=>row.map(csvCell).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
  async function pagedQuery(table,start,end){let all=[];for(let from=0;;from+=1000){let q=db.from(table).select("*").eq("store_id",storeId);q=table==="expenses"?q.is("deleted_at",null).gte("expense_date",start).lte("expense_date",end).order("expense_date"):q.gte("business_date",start).lte("business_date",end).order("business_date");const {data,error}=await q.range(from,from+999);if(error)throw error;all.push(...(data||[]));if(!data||data.length<1000)break}return all}
  function renderFinanceExport(){const {start,end}=monthBounds(financeMonth);$("financeBody").innerHTML=`<div class="card"><div class="section-title">税理士提出用データ</div><div class="finance-form-grid"><div class="field"><label>開始日</label><input type="date" id="exportStart" value="${start}"></div><div class="field"><label>終了日</label><input type="date" id="exportEnd" value="${end}"></div></div><button class="primary" id="exportExpenseCsv">経費CSVを出力</button><button class="secondary" id="exportTaxSalesCsv" style="margin-top:8px">売上CSVを出力</button><div class="finance-note" style="margin-top:10px">CSVは税理士との確認用資料です。税務申告の内容を確定するものではありません。領収書画像は経費一覧から期間別に確認できます。</div></div>`;$("exportExpenseCsv").onclick=async()=>{try{const start=$("exportStart").value,end=$("exportEnd").value,rows=await pagedQuery("expenses",start,end);downloadCsv(`経費_${start}_${end}.csv`,["日付","支払先","金額","カテゴリ","支払方法","メモ","領収書有無","税理士用科目"],rows.map(x=>[x.expense_date,x.vendor,x.amount,x.category,x.payment_method,x.memo,receiptFor(x.id)?"あり":"なし",x.accounting_category]))}catch(e){showStatus(e.message,"error")}};$("exportTaxSalesCsv").onclick=async()=>{try{const start=$("exportStart").value,end=$("exportEnd").value,rows=await pagedQuery("sales",start,end);downloadCsv(`売上_${start}_${end}.csv`,["営業日","売上ID","合計金額","出前・タバコ等","売上実績参考","会計状態","支払方法","精算状態","備考"],rows.map(x=>[x.business_date,x.id,x.total_amount,x.delivery_tobacco_amount,Number(x.total_amount)-Number(x.delivery_tobacco_amount||0),x.payment_status,x.payment_method||"",x.is_settled?"精算済み":"未精算",x.notes]))}catch(e){showStatus(e.message,"error")}}}

  async function renderOwnerFinanceHome(){
    if(!isOwner()){$("ownerFinanceHome")?.remove();return;}
    let box=$("ownerFinanceHome");
    if(!box){
      box=document.createElement("div");box.id="ownerFinanceHome";box.className="owner-finance-home";
      $("homeGoalSection").insertAdjacentElement("afterend",box);
    }
    try{
      const currentMonth=businessDateString().slice(0,7),today=businessDateString();
      await loadFinanceExpenses();
      const s=await monthlyFinance(currentMonth),profit=Number(s.total_sales||0)-Number(s.expense_total||0);
      const todaySales=settledActualForRows(sales.filter(x=>x.business_date===today));
      const goal=Number(s.monthly_goal||0),achievement=goal?`${Math.round(Number(s.total_sales||0)/goal*1000)/10}%`:"未設定";
      const currentExpenses=financeExpenses.filter(x=>String(x.expense_date).startsWith(currentMonth));
      const missing=currentExpenses.filter(x=>!receiptFor(x.id)).length,recent=currentExpenses.slice(0,3);
      box.innerHTML=`<div class="section-title">経営状況</div><div class="metrics owner-home-metrics">${metric("今日の売上",yen(todaySales))}${metric("今月の売上",yen(s.total_sales))}${metric("今月の経費",yen(s.expense_total))}${metric("利益参考値",signedYen(profit))}${metric("未収",yen(s.unpaid_amount),`${s.unpaid_count||0}件`)}${metric("目標達成率",achievement)}</div><button class="attention-item ${missing?"alert":""}" id="openOwnerFinance"><span>領収書未登録 ${missing}件<small>${recent.length?`最近の経費：${recent.map(x=>x.vendor||x.category).join("、")}`:"経費登録はありません"}</small></span><span>›</span></button>`;
      $("openOwnerFinance").onclick=()=>goToPage("finance","経費・収支");
    }catch(e){box.innerHTML='<div class="empty">経営情報を読み込めませんでした</div>'}
  }

  const oldRenderPage=renderPage;renderPage=function(page){if(page==="finance")return void renderFinance();return oldRenderPage(page)};
  const oldGoToPage=goToPage;goToPage=function(page,title){if(page==="finance"&&!isOwner()){showStatus("この画面はオーナーのみ利用できます","error");return oldGoToPage("home","ホーム")}const result=oldGoToPage(page,title);if(page==="finance")requestAnimationFrame(()=>void renderFinance());return result};
  const oldRenderHome=renderHome;renderHome=function(){oldRenderHome();void renderOwnerFinanceHome()};
  const oldApplyRoleNavigation=applyRoleNavigation;applyRoleNavigation=function(){oldApplyRoleNavigation();if(currentPage==="finance"&&!isOwner())currentPage="home"};
  if(typeof renderCashRegisterBeforeExpenses==="function")renderCashRegister=renderCashRegisterBeforeExpenses;
  injectStyle();
})();
