const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const finance=fs.readFileSync(path.join(root,"owner-finance.js"),"utf8");
const settings=fs.readFileSync(path.join(root,"demo-settings.js"),"utf8");
const edge=fs.readFileSync(path.join(root,"supabase/functions/manage-store-members/index.ts"),"utf8");
const migration=fs.readFileSync(path.join(root,"supabase/migrations/20260908100000_expense_management_modes.sql"),"utf8");
const batchMigration=fs.readFileSync(path.join(root,"supabase/migrations/20260908140000_simple_expense_batch.sql"),"utf8");
const permissionMigration=fs.readFileSync(path.join(root,"supabase/migrations/20260908170000_simple_expense_role_permissions.sql"),"utf8");

assert.match(migration,/expense_management_mode in \('simple', 'full', 'disabled'\)/);
assert.match(html,/id="adminExpenseManagementMode"/);
assert.match(html,/備品・消耗品合計/);
assert.match(html,/出前・タバコは含めず/);
assert.match(html,/create_simple_store_expenses/);
assert.match(html,/＋ 金額を追加/);
assert.match(batchMigration,/create or replace function public\.create_simple_store_expenses/);
assert.match(batchMigration,/public\.create_store_expense/);
assert.match(permissionMigration,/manager_simple_expense_permission text not null default 'create'/);
assert.match(permissionMigration,/staff_simple_expense_permission text not null default 'none'/);
assert.match(permissionMigration,/create or replace function public\.simple_expense_access_level/);
assert.match(permissionMigration,/create or replace function public\.update_simple_store_expense/);
assert.match(permissionMigration,/create or replace function public\.delete_simple_store_expense/);
assert.match(permissionMigration,/'備品・消耗品'/);
assert.match(settings,/const expenseManagementMode=/);
assert.match(settings,/簡易管理（備品・消耗品だけ）/);
assert.match(settings,/完全管理（すべての経費・領収書・月次収支）/);
assert.match(finance,/expenseManagementMode\(\)!=="full"/);
assert.match(finance,/expenseManagementMode\(\)==="simple"\?quickExpenseCashRegister\(\):cashRegisterWithoutExpense\(\)/);
assert.match(edge,/expense_management_mode: expenseManagementMode/);
console.log("Expense management mode checks passed.");
