const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const js=fs.readFileSync(path.join(root,"owner-finance.js"),"utf8");
const sql=fs.readFileSync(path.join(root,"supabase/migrations/20260909120000_sale_expense_classification.sql"),"utf8");
const {chromium}=require("C:/Users/jojoj/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
assert.match(sql,/create table if not exists public\.sale_expense_allocations/);
assert.match(sql,/create table if not exists public\.sale_expense_receipts/);
assert.match(sql,/store_uses_full_expense_management\(store_id\)/);
assert.match(sql,/replace_sale_expense_allocations/);
assert.match(sql,/allocation_total <> source_amount/);
assert.match(sql,/replace_sale_expense_receipt/);
assert.match(sql,/'total_sales',coalesce\(sum\(s\.total_amount\)/);
assert.match(sql,/'expense_total',manual_total\+sale_cost_total/);
assert.match(sql,/'未整理（出前・タバコ等）'/);
assert.match(js,/expenseManagementMode\(\)!=="full"/);
assert.match(js,/この機能はオーナー専用です/);
assert.match(js,/売上入力の金額/);
assert.match(js,/内訳合計を売上入力の金額/);
assert.match(js,/SALE_COST_CATEGORIES=\["出前","タバコ","その他"\]/);
assert.match(js,/replace_sale_expense_allocations/);
assert.match(js,/replace_sale_expense_receipt/);
assert.match(js,/delete_sale_expense_receipt/);
assert.match(js,/経費には一度だけ計上されます/);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:"C:/Program Files/Google/Chrome/Application/chrome.exe"}),page=await browser.newPage({viewport:{width:390,height:844}});
await page.route("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2",r=>r.fulfill({contentType:"application/javascript",body:`window.supabase={createClient(){return {auth:{getSession:async()=>({data:{session:null},error:null}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}}}};`}));
await page.route("https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js",r=>r.fulfill({contentType:"application/javascript",body:"window.Chart=class{destroy(){}update(){}}"}));
await page.goto(`file:///${path.join(root,"index.html").replaceAll("\\","/")}`);
const result=await page.evaluate(async()=>{currentAuthUser={id:"owner"};currentStoreMember={user_id:"owner",role:"owner"};storeId="store";platformAdminMode=false;storeOperatingSettings={expense_management_mode:"full"};customers=[{id:"customer-1",name:"田中様"}];sales=[{id:"sale-1",store_id:"store",business_date:businessDateString(),customer_id:"customer-1",total_amount:50000,delivery_tobacco_amount:10000,payment_status:"回収済み",payment_method:"現金",is_settled:true}];
const tableData={expenses:[],expense_receipts:[],sale_expense_allocations:[],sale_expense_receipts:[]};
const query=data=>{const q={select(){return q},eq(){return q},is(){return q},order(){return q},limit(){return q},gte(){return q},lte(){return q},range(){return q},then(resolve){resolve({data,error:null})}};return q};let saved=null;
db.from=table=>query(tableData[table]||[]);db.rpc=async(name,args)=>{if(name==="get_owner_monthly_finance")return{data:{total_sales:50000,expense_total:10000,sale_expense_total:10000,category_expenses:[{category:"未整理（出前・タバコ等）",amount:10000}]},error:null};if(name==="replace_sale_expense_allocations"){saved=args;return{data:{},error:null}}return{data:null,error:null}};
applyRoleNavigation();goToPage("finance","経費・収支");await new Promise(r=>setTimeout(r,80));document.querySelector('[data-ft="expenses"]').click();await new Promise(r=>setTimeout(r,80));const sourceShown=document.getElementById("ownerFinanceRoot").textContent.includes("田中様")&&document.getElementById("ownerFinanceRoot").textContent.includes("要整理");document.querySelector('[data-edit-sale-cost="sale-1"]').click();document.querySelector(".sale-cost-amount").value="4000";document.getElementById("addSaleCostAllocation").click();const amounts=document.querySelectorAll(".sale-cost-amount");amounts[1].value="6000";document.querySelectorAll(".sale-cost-category")[1].value="タバコ";document.getElementById("saveSaleCostAllocations").click();await new Promise(r=>setTimeout(r,80));currentStoreMember.role="manager";applyRoleNavigation();const ownerMenuHidden=document.querySelector('.drawer-link[data-page="finance"]').classList.contains("hidden");return{sourceShown,savedTotal:saved.target_allocations.reduce((n,x)=>n+x.amount,0),categories:saved.target_allocations.map(x=>x.category),ownerMenuHidden}});
assert.deepEqual(result,{sourceShown:true,savedTotal:10000,categories:["出前","タバコ"],ownerMenuHidden:true});await browser.close();console.log("Sale expense classification checks passed.")})().catch(error=>{console.error(error);process.exit(1)});
