const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),js=fs.readFileSync(path.join(root,"owner-finance.js"),"utf8"),sql=fs.readFileSync(path.join(root,"supabase/migrations/20260909140000_tax_accountant_exports.sql"),"utf8"),html=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(html,/owner-finance\.js\?v=20260909-2/);
assert.match(sql,/get_owner_sales_export_rows/);
assert.match(sql,/get_owner_expense_export_rows/);
assert.match(sql,/store_uses_full_expense_management\(target_store_id\)/);
assert.match(sql,/left join public\.customers customer/);
assert.match(sql,/left join public\.employees account/);
assert.match(sql,/left join auth\.users creator/);
assert.match(sql,/sale_payment_events event/);
assert.match(sql,/SALEEXP-/);
assert.match(sql,/receipt\.storage_path/);
assert.match(js,/月次収支サマリーCSVを出力/);
assert.match(js,/経費明細CSVを出力/);
assert.match(js,/売上明細CSVを出力/);
assert.match(js,/領収書画像をZIPで保存/);
assert.match(js,/\["営業日","売上ID","顧客名","口座名","入力者"/);
assert.match(js,/\["管理番号","種別","日付","支払先・顧客"/);
assert.match(js,/loaded>104857600/);
const start=js.indexOf("let zipCrcTable=null;"),end=js.indexOf("const zipFileName",start);assert.ok(start>0&&end>start);
const context={TextEncoder,Uint8Array,DataView,Date};vm.createContext(context);vm.runInContext(js.slice(start,end)+"this.zip=storedZip([{name:'領収書一覧.csv',data:new TextEncoder().encode('ok')},{name:'領収書/EXP-1_test.jpg',data:new Uint8Array([1,2,3,4])}]);",context);
const zip=Buffer.from(context.zip),view=new DataView(zip.buffer,zip.byteOffset,zip.byteLength),eocd=zip.length-22;
assert.equal(view.getUint32(0,true),0x04034b50);assert.equal(view.getUint32(eocd,true),0x06054b50);assert.equal(view.getUint16(eocd+10,true),2);assert.equal(view.getUint32(view.getUint32(eocd+16,true),true),0x02014b50);
console.log("Tax accountant export checks passed.");
